feat: update doc for optscale version
hystax/optscale pull request #160
Opened 2023-11-09 11:31 UTC by tguisep

Hello,

I tried to update my optscale instance to integrate lasts update.
But I took time understand the new deployment parameter.
<version>

Thomas.

2023-11-09 11:51 UTC, maxb-hystax requested changes

2023-11-09 11:51 UTC, maxb-hystax commented on README.md
> +**version**: OptScale git tag (eg: 2023110701-public)
I would specify that this is applicable if you use versions with images hosted on dockerhub (every *-public tag also has corresponding tag in dockerhub). If you build some version locally - it can be just tag of your local images

2023-11-10 05:31 UTC, maxb-hystax approved these changes

2023-11-10 05:31 UTC, nexusriot approved these changes

2023-11-10 05:33 UTC, merged